### ISSUE TITLE
Unable to install on ARM (Beaglebone Black)

### ISSUE THREAD

**Issue by me21** [tsukumijima/netifaces-plus#1]
```
debian@evolve-1:~/evolve_web$ venv/bin/pip3 install netifaces-plus
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement netifaces-plus (from versions: none)
ERROR: No matching distribution found for netifaces-plus
```

**Comment by me21** [comment]
I was able to build wheel and install it locally by following the instructions at https://packaging.python.org/en/latest/tutorials/packaging-projects/ (cloning the repo, running `python3 -m pip install --upgrade build` and `python3 -m build`)

**Comment by mapi68** [comment]
This is the zip file for armv7l: inside there is netifaces_plus-0.12.3-cp311-cp311-linux_armv7l.whl


[netifaces_plus-0.12.3-cp311-cp311-linux_armv7l.zip](https://github.com/user-attachments/files/17860925/netifaces_plus-0.12.3-cp311-cp311-linux_armv7l.zip)

**Comment by tsukumijima** [comment]
The latest version supports Linux armv7l.
