### ISSUE TITLE
bug: Segmentation fault when ifa_addr is NULL

### ISSUE THREAD

**Issue by serverwentdown** [tsukumijima/netifaces-plus#2]
https://github.com/tsukumijima/netifaces-plus/blob/1f4c2a134a74c29e73274820ee190e878c100330/netifaces/_netifaces.c#L1265

In cases where ifa_addr is NULL (interfaces without a link-layer like Tailscale, or dial-up connections via PPP), this line of code causes a segmentation fault.

**Comment by tsukumijima** [comment]
I apologize, but I only managed to update the netifaces library, which had finished being maintained. I'm not particularly knowledgeable about its internal implementation and I don't have much knowledge about C language either.

While pull requests are very welcome, I can't make corrections myself.

As I have written in the readme, personally, I think the https://pypi.org/project/ifaddr/ library is better as it is implemented purely in Python and its maintenance continues. Currently, I am using it and I do not use this library.

**Comment by ntamas** [comment]
This issue should now be fixed by #4. @tsukumijima Is there a chance to make a new official release with this fix included?

**Comment by tsukumijima** [comment]
v0.12.2 has been released. It will probably be fixed, so I will close this Issue.
https://github.com/tsukumijima/netifaces-plus/releases/tag/release_0_12_2
