### ISSUE TITLE
Release for Python 3.12?

### ISSUE THREAD

**Issue by ntamas** [tsukumijima/netifaces-plus#3]
Hello! Is there going to be a new release of `netifaces-plus` with pre-built wheels for Python 3.12 now that 3.12.0 is out? If you don't have time to do it yourself, will you accept and merge a PR that bumps `cibuildwheel` in Github Actions so it builds wheels for Python 3.12?

**Comment by tsukumijima** [comment]
I have released netifaces-plus v0.12.1, which is able to build wheel for Python 3.12.
It will probably be automatically uploaded to PyPI once the CI build from https://github.com/tsukumijima/netifaces-plus/actions/runs/6483815656 is complete.
(note that I don't have Python 3.12 installed in my development environment yet, so I haven't tested it.)

**Comment by ntamas** [comment]
Thanks, it works!
